environment:
  matrix:
    - CMAKE_BUILD_TYPE: "Debug"
    - CMAKE_BUILD_TYPE: "Release"
build_script:
  # Fix "sh.exe" path variable to compile using MinGW Makefiles
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=C:\MinGW\bin;%PATH%
  - mkdir build
  - cd build
  - cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% ..
  - cmake --build .
